### PR TITLE
Add ldap data message parsing specific to Microsoft LDAP

### PR DESCRIPTION
**Pull request by cuteboi**
This is in regards to #35

### CODE REVIEW

**Comment by vesse** [comment]
Thanks, this will be very useful - would have needed this already in a project I did at work.

But please fix the code so that current tests pass (check that `err.message` exists before trying to match, check that `ldapComment` exists), and also see if you could add a test that makes the current `test/ldapserver.js` return an AD style message that could verify the new functionality (without adding `message` to every response, this would eg. fix the tests for your code but then it would fail if there is no message or no match).

Also, please change the switch to lookup table, in my opinion it would greatly improve readability (initialize the table, then just `message = messages[ldapContextError] || messages['default'];`)

**Comment by cuteboi** [comment]
I'm not adept enough to work out how to return error messages from ldapjs instances. I see the InvalidCredentialsError(), but it isn't documented, and source for that project is a little obscure for me.

I've committed the latest changes, should work with tests now, but I can't figure out how to generate proper error messages for code 49 (Invalid Credentials) with "message"

**Comment by cuteboi** [comment]
Oh, took a few steps, but here we go:  https://travis-ci.org/Korcett/passport-ldapauth

**Comment by vesse** [comment]
Cool, thanks! I'll check and finalize this on the weekend.

**Pull request merged**
