### PR TITLE
Only catch the 'error' event once.

### PR DESCRIPTION
**Pull request by ddolcimascolo**
Works around https://github.com/vesse/node-ldapauth-fork/issues/53

### CODE REVIEW

**Comment by ddolcimascolo** [comment]
Tests are still green, dunno if you would like to see some new tests...

**Comment by ddolcimascolo** [comment]
@vesse did you get a chance to review this?

**Comment by ddolcimascolo** [comment]
Hello @vesse

It's been a month without hearing from you. Maybe you're not monitoring this anymore and you're looking for volunteers to help maintain this repo. If so, I'd be happy to help! 

Regards, 
David

**Comment by vesse** [comment]
Hi @ddolcimascolo 

Yes, i was hoping to fix things better as vesse/node-ldapauth-fork#69 should make it possible to use the same client instead of recreating one on every authenticate request, but it has come clear that I won't be having any time (nor real use case) to do that.

I'll merge and release this later today as I don't have my laptop with me now.

**Comment by ddolcimascolo** [comment]
Thx for the merge

David

**Comment by Sczlog** [comment]
It looks like doesn't totally fix this problem.
ldapauth will pass error to callback, and if it is an others error, it will call `handleError` function.
This error will also been emitted by eventemitter, which make.
I'm using passport-ldap and then I found if I use multiple strategy, then it will fire `attempts` twice time, make following passport strategy called twice.

see the callstack, trigger by one error

image

image

**Pull request merged**
